CREATE TABLE IF NOT EXISTS teachers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  department TEXT NOT NULL,
  subjects TEXT NOT NULL,
  office TEXT NOT NULL,
  phone TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS office_hours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  day TEXT NOT NULL CHECK (day IN ('Mon', 'Tue', 'Wed', 'Thu', 'Fri')),
  period INTEGER NOT NULL CHECK (period BETWEEN 1 AND 8)
);

CREATE INDEX IF NOT EXISTS idx_office_hours_teacher_id ON office_hours(teacher_id);
CREATE INDEX IF NOT EXISTS idx_office_hours_day_period ON office_hours(day, period);
